### ISSUE TITLE
Tagged Version 1.0.2 is incorrect, it's in fact v1.0.1

### ISSUE THREAD

**Issue by ghost** [huangguozhen/paho.mqtt.js#1]
your tagged v1.0.2 is wrong, because it's v1.0.1

make a diff with the original and you'll see that it's the same file:
https://raw.githubusercontent.com/eclipse/paho.mqtt.javascript/v1.0.1/src/mqttws31.js

whereas the original v1.0.2 is different:
https://raw.githubusercontent.com/eclipse/paho.mqtt.javascript/v1.0.2/src/mqttws31.js

very mis-leading, esp that it's on bower registry...

**Comment by huangguozhen** [comment]
sorry for my mistake.
I have remove the tag 1.0.2 . fix it at tag 2.0.4 sync with npm registry.
