### ISSUE TITLE
Paho.mqtt.js on Node

### ISSUE THREAD

**Issue by minhnhatspk** [huangguozhen/paho.mqtt.js#3]
When I using declare on Node:
var PahoMQTT = require('paho.mqtt.js')
client = new PahoMQTT.Client(location.hostname, Number(location.port), "clientId");

I have error: PahoMQTT.Client is not a constructor.
What I have to do now?

**Comment by huangguozhen** [comment]
I am sorry there is a misstake on Node, I have fix the bug and upgrade the package paho.mqtt.js@2.0.5.
You can upgrade the package paho.mqtt.js@2.0.5, see the diff [Fix Paho.mqtt.js on Node #3](https://github.com/huangguozhen/paho.mqtt.js/commit/6c64d76c563afd699c73d7e47133aecd7788c239)
```
          return factory(root)
        });
      } else if (typeof exports === 'object') {
 -      factory(root);
 +      module.exports = factory(root);
      } else {
        if (typeof root.Paho === 'undefined') {
          root.Paho = {};
```
